services:
  postgres:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
  debezium-kafka-connect:
    image: "debezium/connect"
    container_name: "debezium-kafka-connect"
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: "debezium-kafka-connect-group"
      CONFIG_STORAGE_TOPIC: "debezium-kafka-config-topic"
      OFFSET_STORAGE_TOPIC: "debezium-kafka-offset-topic"
      ADVERTISED_HOST_NAME: debezium-kafka-connect
      ADVERTISED_PORT: 8083
      BOOTSTRAP_SERVERS: "kafka:9092"
  kafka-ui:
    image: "provectuslabs/kafka-ui:latest"
    ports:
      - "8081:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
      DYNAMIC_CONFIG_ENABLED: "true"
  schema-registry:
    image: "bitnami/schema-registry:latest"
    container_name: "schema-registry"
    ports:
      - "8082:8081"
    environment:
      SCHEMA_REGISTRY_KAFKA_BROKERS: "PLAINTEXT://kafka:9092"
      SCHEMA_REGISTRY_ADVERTISED_HOSTNAME: "schema-registry"
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
      SCHEMA_REGISTRY_CLIENT_AUTHENTICATION: "NONE"
      SCHEMA_REGISTRY_DEBUG: "true"
  kafka:
    image: "bitnami/kafka:3.2.3"
    container_name: "kafka"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:9093
      - ALLOW_PLAINTEXT_LISTENER=YES
  app:
    image: "event-outbox:latest"
    pull_policy: if_not_present
    ports:
      - "8080:8080"
